comment:
  require_changes: yes

# Keeping it 100! If you're looking to change that, either:
# - Go add a test!
# - Only for extreme cases: exclude the line from kcov https://www.mankier.com/1/kcov#--exclude-pattern
coverage:
  range: 100..100
  status:
    project:
      default:
        base: pr
        target: 100%
        threshold: 0%
    patch:
      default:
        base: pr
        target: 100%
        threshold: 0%
  round: down
  precision: 0
